<?php
  $statuses = [
    array("id" => 1, "user" => 1, "status" => "This is a cool status"),
    array("id" => 2, "user" => 2, "status" => "This is a cool status"),
    array("id" => 3, "user" => 3, "status" => "This is a cool status"),
    array("id" => 4, "user" => 4, "status" => "This is a cool status"),
    array("id" => 5, "user" => 1, "status" => "This is a cool status"),
    array("id" => 6, "user" => 2, "status" => "This is a cool status"),
    array("id" => 7, "user" => 3, "status" => "This is a cool status"),
    array("id" => 8, "user" => 4, "status" => "This is a cool status"),
    array("id" => 9, "user" => 1, "status" => "This is a cool status"),
    array("id" => 10, "user" => 2, "status" => "This is a cool status"),
    array("id" => 11, "user" => 3, "status" => "This is a cool status"),
    array("id" => 12, "user" => 4, "status" => "This is a cool status"),
    array("id" => 13, "user" => 1, "status" => "This is a cool status"),
    array("id" => 14, "user" => 2, "status" => "This is a cool status"),
    array("id" => 15, "user" => 3, "status" => "This is a cool status"),
    array("id" => 16, "user" => 4, "status" => "This is a cool status"),
    array("id" => 17, "user" => 1, "status" => "This is a cool status"),
    array("id" => 18, "user" => 2, "status" => "This is a cool status"),
    array("id" => 19, "user" => 3, "status" => "This is a cool status"),
    array("id" => 20, "user" => 4, "status" => "This is a cool status"),
    array("id" => 21, "user" => 1, "status" => "This is a cool status"),
    array("id" => 22, "user" => 2, "status" => "This is a cool status"),
    array("id" => 23, "user" => 3, "status" => "This is a cool status"),
    array("id" => 24, "user" => 4, "status" => "This is a cool status"),
    array("id" => 25, "user" => 1, "status" => "This is a cool status"),
    array("id" => 26, "user" => 2, "status" => "This is a cool status"),
    array("id" => 27, "user" => 3, "status" => "This is a cool status"),
    array("id" => 28, "user" => 4, "status" => "This is a cool status"),
    array("id" => 29, "user" => 1, "status" => "This is a cool status"),
    array("id" => 30, "user" => 2, "status" => "This is a cool status"),
    array("id" => 31, "user" => 3, "status" => "This is a cool status"),
    array("id" => 32, "user" => 4, "status" => "This is a cool status"),
    array("id" => 33, "user" => 1, "status" => "This is a cool status"),
    array("id" => 34, "user" => 2, "status" => "This is a cool status"),
    array("id" => 35, "user" => 3, "status" => "This is a cool status"),
    array("id" => 36, "user" => 4, "status" => "This is a cool status"),
    array("id" => 37, "user" => 1, "status" => "This is a cool status"),
  ]
?>
