<?php
  $statuses = [
    array("id" => 1, "user" => 1, "status" => "Spring break is sooooo welcome! Going hiking in Yosemite!!"),
    array("id" => 2, "user" => 2, "status" => "A classmate of mine is training for the Indianapolis marathon in May and this has inspired me to run 13.1 miles too."),
    array("id" => 3, "user" => 3, "status" => "Today I ran 8 miles along the Golden Gate Park to Ocean Beach and back."),
    array("id" => 4, "user" => 4, "status" => "Jogged along the Embarcadero to AT&T stadium, home of the #Giants. Iconic!! Hope to watch a game soon."),
    array("id" => 5, "user" => 1, "status" => "Been running for 2 months in SF. Getting used to the hills, running on flat routes is now a piece of cake!"),
    array("id" => 6, "user" => 2, "status" => "Sally Challenge is on! 30 days to completing the whole song. What did I get myself into?"),
    array("id" => 7, "user" => 3, "status" => "I really need to protein-load, but I love cold pizzas."),
    array("id" => 8, "user" => 4, "status" => "It's Saturday night and here I am posting statuses instead of resting to be ready for my Sunday run."),
    array("id" => 9, "user" => 1, "status" => "Looking back at Emily Blunt's workout for Edge of Tomorrow, I'm getting a motivation boost."),
    array("id" => 10, "user" => 2, "status" => "Spring break is sooooo welcome! Going hiking in Yosemite!!"),
    array("id" => 11, "user" => 3, "status" => "I did it! Ran 13.1 miles all by myself."),
    array("id" => 12, "user" => 4, "status" => "Wonder what it would be like to run in Yosemite or Death Valley. Can't wait!"),
    array("id" => 13, "user" => 1, "status" => "People ask me how can I run without music. After a while you just don't think about it."),
    array("id" => 14, "user" => 2, "status" => "I don't mind music but can't be bothered to run with my phone haha"),
    array("id" => 15, "user" => 3, "status" => "SF does have plenty of flat routes. Check out the Embarcadero."),
    array("id" => 16, "user" => 4, "status" => "When you have to post about your run while running"),
    array("id" => 17, "user" => 1, "status" => "Holberton School has managed to make push ups fun"),
    array("id" => 18, "user" => 2, "status" => "Pull ups too"),
    array("id" => 19, "user" => 3, "status" => "Docker organizes 3 mile runs"),
    array("id" => 20, "user" => 4, "status" => "Makerun all routes clean"),
    array("id" => 21, "user" => 1, "status" => "Why would you want more statuses"),
    array("id" => 22, "user" => 2, "status" => "This is a new status"),
    array("id" => 23, "user" => 3, "status" => "This is another new status"),
    array("id" => 24, "user" => 4, "status" => "And another one"),
    array("id" => 25, "user" => 1, "status" => "And another one"),
    array("id" => 26, "user" => 2, "status" => "4"),
    array("id" => 27, "user" => 3, "status" => "3"),
    array("id" => 28, "user" => 4, "status" => "2"),
    array("id" => 29, "user" => 1, "status" => "1"),
    array("id" => 30, "user" => 2, "status" => "Stop"),
    array("id" => 31, "user" => 3, "status" => "Seriously"),
    array("id" => 32, "user" => 4, "status" => "You're killing me"),
    array("id" => 33, "user" => 1, "status" => "This is not an infinite statuses load"),
    array("id" => 34, "user" => 2, "status" => "Try me"),
    array("id" => 35, "user" => 3, "status" => "Fine!"),
    array("id" => 36, "user" => 4, "status" => "Penultimate status"),
    array("id" => 37, "user" => 1, "status" => "Told you"),
  ]
?>
